version: '3.8'

services:
  postgres:
    image: postgres
    container_name: kanban001db
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "kanban001db"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # diretório local do repositório
    restart: unless-stopped

volumes:
  postgres_data: